samples:
    Con_1:
      F: Con_1_1.fq.gz
      R: Con_1_2.fq.gz
    Con_2:
      F: Con_2_1.fq.gz
      R: Con_2_2.fq.gz
    Con_3:
      F: Con_3_1.fq.gz
      R: Con_3_2.fq.gz
    T_120d_1:
      F: T_120d_1_1.fq.gz
      R: T_120d_1_2.fq.gz
    T_120d_2:
      F: T_120d_2_1.fq.gz
      R: T_120d_2_2.fq.gz
    T_120d_3:
      F: T_120d_3_1.fq.gz
      R: T_120d_3_2.fq.gz
reads_folder: reads


reference_base: Data/hg38_rna
salmon_bootstraps: 3

# Differential Analysis
metadata_file: meta.txt
sample_column: Sample
experiments:
  120d:
    prefix: 120d
    filter: Time == '120d' | Time == '0'
    PCA_Group: Time
    design: Time
    contrast: c('Time', '120d', '0')
    display_column: Sample
  220d:
    prefix: 220d
    filter: Time == '120d' | Time == '0'
    PCA_Group: Time
    design: Time
    contrast: c('Time', '120d', '0')
    display_column: Sample
#  Early_v_Late:
#    prefix: Early_v_Late
#    filter: Group == 'Early' | Group == 'Late'
#    PCA_Group: Group
#    design: Group
#    contrast: c('Group', 'Early', 'Late')
#    display_column: Sample
