samples:
    Con_1:  Con_1
    Con_2:  Con_2
    Con_3:  Con_3
    T_120d_1: T_120d_1
    T_120d_2: T_120d_2
    T_120d_3: T_120d_3
reads_folder: reads
input_file_suffix: .fq.gz
reference_base: Data/hg38_rna
salmon_bootstraps: 3

# Differential Analysis
metadata_file: meta.txt
tx2gene: Data/IDs
sample_column: Sample
organism: org.Hs.eg.db
experiments:
  120d:
    prefix: 120d
    filter: Time == '120d' | Time == '0'
    PCA_Group: Time
    design: Time
    contrast: c('Time', '120d', '0')
    display_column: Sample
  Early_v_Late:
    prefix: Early_v_Late
    filter: Group == 'Early' | Group == 'Late'
    PCA_Group: Group
    design: Group
    contrast: c('Group', 'Early', 'Late')
    display_column: Sample
